language: java
addons:
  sonarcloud:
    organization: "cfc-kata"
    token:
      secure: "I1BMSU7D1ogQjqvvwzwZfs/W9vZ37nb8ZJKkc4Vi8ribzTYaD6KVVJCtg3RcNALccnIGP9a7rs+LlyhMWJ428lBrNKSzOQ797vJTBUmJyc9qmOLtFo+JvWiWPMZLeyYIC7eKfxjvkz3bdbM1zj1dFwOTVagu6or63cB/Jyg/AcK8UWfaPOT8ywTuD2tTh4Z5SWxQLqPZorgMXZQkt7EDxduQd7egHjD32R1SZBKxsQAfKZ45bQRLnwmICRjuVxBZqDPJXuys+tcUOfcorBiYY136uyBCuvAsd6nRUcRZh6u+WtZrTMKI5tMHPc/UqJJo/FvjlEweX60RhXlf3noZlv8VrtsbHds672zri/P8lwJ+74RunFnf0QV/TNntkzOoYdSoKYIGDm3VYfCsza2XhdIGEbpZUwi3g89tuLTnFPAyeC3eyXYq2ucLBig9gV5hQ7LJTSqUQc/uf3Je7gx1ZJqeluUGDyM2vA/4cEf0An6AqE12DpfhhVp6Q9YHAJWnilADNhL7ErGdjwd9qg6eTfDkyL4AOpwVpn/AKyyPA5S5zpAsa3QQoV+GiY5L4xLQTZgK3bix9srZRW8S5X1zwm99sbyN689cnvfzTFu/DARtIW08LXnWZFZnWlr8ElTVraP2QuoYpnVsg1rNBCOboU08XO/qlc/kMmkXWgZkojc="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cfc-kata_cfc-kata-loan-team-b
